### ISSUE TITLE
Intermittent segmentation fault

### ISSUE THREAD

**Issue by socalvin** [ibmdb/ruby-ibmdb#11]
The segmentation fault causes Unicorn worker (running the ibm_db gem) dead and an error page is displayed on the browser. We provide the dump file to NewRelic for analysis and the feedback is that it is caused by the C-extension shipped with ibm_db gem.

NewRelic ticket: https://support.newrelic.com/requests/119846#/satisfaction

The dump file can be download from the above NewRelic ticket. Thanks!

**Comment by flavorjones** [comment]
Most likely this is the C extension overwriting memory beyond the requested size, thereby trashing the heap's metadata, thereby causing segfaults during allocation. This is easy to catch with valgrind; in fact, valgrind will tell you exactly when any invalid memory operations occur, which is usually in a completely different code path than the segfault (because the segfault happens much later, during a different operation).

But valgrind is *extremely* slow, as it's emulating the chipset. So I usually like to be as focused as possible with it.

Plan A: see if valgrind catches anything during a test suite run. Have we tried this?

Plan B: reproduce the issue while running inside valgrind, presuming it's easy to reproduce.

Plan C: someone experienced with C extensions needs to stare at the code with their eyeballs and see if they spot anything. 

There is no plan D.

**Comment by flavorjones** [comment]
I tried running the unit test suite, but it's not exercising the C extension. If anyone gets the ActiveRecord test suite running against db2, I'm happy to assist in running it under valgrind. Let me know.

**Comment by berlin-ab** [comment]
To add a data point here:  our team regularly gets segmentation faults while running out test suite, development application, and production application.  We see the segfault multiple times an hour during development and multiple times a day in production.

**Comment by arvindgu** [comment]
@berlin-ab Could you please confirm the version of ruby, rails and ibm_db gems. Could you please share the dumps.

**Comment by berlin-ab** [comment]
@arvindgu Ruby 2.2.2, 2.2.3.  Rails 4.2.4, 4.2.3, 4.2.2, 4.2.1.  ruby-ibmdb versions 2.5.26, 2.5.27, 2.6.0, 2.6.1.

We're also using the Sequel gem.  The issue should be easy to replicate by loading a bunch of data from a database.  We're able to consistently replicate it by creating 1M records, and then trying to load them from the database.  At some point garbage collection happens, and a segmentation fault occurs.

**Comment by akhilravuri1** [comment]
Hi @socalvin 
we have released a new version in the ibm_db driver which supports till 2.6.5 and rails v6.
Please update the driver.
Thanks,
Akhil
