### ISSUE TITLE
Error while installing ibm_db gem:- unknown option: -R$ORIGIN/clidriver/lib

### ISSUE THREAD

**Issue by myamun** [ibmdb/ruby-ibmdb#47]
On Mac El Capitan 10.11.2 version, bundle install fails when installing _ibm_db_ gem. 
I was able to install the gem manually using the command: 

    gem install ibm_db (2.6.1 universal-darwin-14)
But when I do a _bundle install_ it fails with below error.
``` 
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/ myamun/.rvm/rubies/ruby-2.0.0-p598/bin/ruby -r ./siteconf20151228-798-13gznvv.rb extconf.rb
Detected 64-bit Ruby
 
creating gil_release_version
creating unicode_support_version
checking for SQLConnect() in -ldb2... yes
checking for gil_release_version... yes
checking for unicode_support_version... yes
creating Makefile
....
linking shared-object ibm_db.bundle
ld: unknown option: -R$ORIGIN/clidriver/lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ibm_db.bundle] Error 1

make failed, exit code 2 
```

Is there a way I can provide _platform_ in my Gemfile to replicate the command that was run manually or is there something else that I would have to do?

**Comment by arvindgu** [comment]
In ruby interactive command, what is the output of  *RUBY_PLATFORM* ?

**Comment by myamun** [comment]
The output of _RUBY_PLATFORM_ is  "x86_64-darwin15.2.0"

**Comment by arvindgu** [comment]
When you issue bundle install, I see in your error, extconf.rb is invoked instead of extconf_MacOS.rb to install ibm_db gem on Mac OS platform. The extconf_MacOS.rb should be invoked for darwin platform. 

Did you copy Rails project from Linux or some other platform?

If this is not a new Rails application, can you please try creating a new sample Rails application with ibm_db gem and check whether the bundle install still fails.

I would like to know whether ibm_db gem installation is successful without specifying any option, Can you please uninstall the ibm_db gem. Run *gem uninstall ibm_db*  
Then install ibm_db gem.  Run *gem install ibm_db*
Please provide the error log, if any error comes.

**Comment by myamun** [comment]
Also to clarify this is not Rails but just a ruby based test automation project which was initially developed on Windows and now ported to Mac.

I followed the steps that you mentioned. Uninstalled and re-installed ibm_db, I get the same error that I had posted earlier.

**Comment by hbergy** [comment]
I also have this problem.  I noticed that rubygems.org only has a platform specific gem for x86_64-darwin-14, not for darwin 15.  Could that be the problem?

**Comment by arvindgu** [comment]
We are looking into this issue. Meanwhile could you please fill this form  http://goo.gl/forms/EKzg7A6HZw

**Comment by arvindgu** [comment]
Today, we have released new version of ibm_db gem **3.0.1** to fix the installation problem in El Capitan. Please try it and let us know.

**Comment by hbergy** [comment]
Thanks.  3.0.1 fixed it for me

**Comment by arvindgu** [comment]
Can this be closed?
