### ISSUE TITLE
Odd behavior

### ISSUE THREAD

**Issue by skcord** [ibmdb/ruby-ibmdb#7]
Hello:

I am seeing some odd, and unpredictable, behavior.  Rarely, a query returns without issue.  Sometimes, a query only returns a fraction of the known rows.  Mostly, I receive this cryptic message:
uncaught throw :"Fetch Failure: <error message could not be retrieved>".  This occurs whether I use fetch_array or fetch_assoc.  Please advise.  Thank you.

Windows Server 2008 R2 Enterprise (x64)
ruby 1.9.3p484 (2013-11-22) [i386-mingw32]
Rails 4.0.2
ibm_db (2.5.18 x86-mingw32, 2.5.17 x86-mingw32)

![ibm_db_error](https://cloud.githubusercontent.com/assets/7861168/5000725/4eb841c4-69a3-11e4-91b5-d3e830760d3e.png)

**Comment by aaronbartell** [comment]
I am getting this same intermittent error.  Note I am on IBM i and using `DB2 for i`.  Did @skcord or @praveend find resolutions to this?

**Comment by arvindgu** [comment]
@aaronbartell Could you please collect CLI traces and share with us. Also please provide details of Ruby version, ibm_db gem version, Platform. If you can provide a sample repro that will expedite the investigation.

**Comment by arvindgu** [comment]
Its been long time, and I have not got any update for CLI trace, and Ruby version, ibm_db gem version and Platform details. I am closing this for now. It can be reopened with provided the details I asked in my previous update.

**Comment by rabos5** [comment]
Any updates here?

**Comment by akhilravuri1** [comment]
Hi @rabos5 
we working on it.
we are planning to support the latest versions of ruby and rails also.

Thanks,
Akhil

**Comment by rabos5** [comment]
Hi @akhilravuri1 

I'm facing the same issue as mentioned by **skcord** when the issue was initially opened albeit several years later with newer versions of things.  Here's what I got:

- Ruby Version = 2.6.5
- ibm_db gem = 4.0.0
- activemodel, activerecord, activesupport gems = 5.1.1
- arel gem ~> 8.0
- IBM_DB.client_info(conn) -> @DRIVER_NAME="libdb2.a", @DRIVER_VER="10.05.0005", @DRIVER_ODBC_VER="03.51", @ODBC_VER="03.01.0000"
- IBM_DB.server_info(conn) -> @DBMS_NAME="DB2", @DBMS_VER="11.01.0005"
- not using Rails
- will be integrating the use of concurrent-ruby ~> 1.1.5

It would definitely be helpful if there were any documentation listing out suggestions of the different versions for all the pieces as far as compatibility goes (everything listed above).

Main use case I'm going after is pulling data out of DB2 via SQL select statements.  Last thing I'll mention, seg faults are not uncommon in my experience using all of this.

Do you guys have an expected release date for that latest version?

Thanks in advance for your help!

Ryan
