### ISSUE TITLE
rake db:drop/db:create issue

### ISSUE THREAD

**Issue by lrcrews** [ibmdb/ruby-ibmdb#9]
Hello again,

The inability to perform 'rake db:drop' and 'rake db:create' is actually a rather annoying one for those of us who use RSPEC (or other testing frameworks) as we have to manually go in and drop the test table, then create it again, then run 'rake db:schema:load' every single time.

Is there any chance this issue may be addressed?

Thanks,
~ Ryan

**Comment by praveend** [comment]
Hi @nilbus 

To create a database or drop, one will need to connect (called attach) to the instance of DB2 rather than any particular database. When needed to perform create/drop database operation from rails we are knowingly bypassing the connection attempt to database (flow after line 192) [when we see dbops set to true, meaning this connection attempt is for db operations]...In order to not change/introduce any code but be able to reuse we intialize the IBM_DBAdapter class as earlier with no connection object.

Assumption here is that an initialization attempt here would be made only for create/drop database purpose (as did in the database.rake) and then we would internally attach to instance when the create_database or drop_database method is called. (check def build_conn_str_for_dbops() @ line 1549 and line 1591).

code @ line 655 would not kick in until a schema is specified. I had not tried with explicit mention of schema and hence did not hit any issues. Yes, if a schema is specified explicitly and other than the mentioned username it could fail down the flow when trying to set the schema (we should restrict this operation when performing dbops).

The gist is based on Rails 4.1.8

Thanks

Praveen

**Comment by milloslex** [comment]
hi

I Replace the active_record.rb file in $GEM_HOME/gems/activerecord-4.1.x/lib/ with the one in gist

Replace the database_tasks.rb file in $GEM_HOME/gems/activerecord-4.1.x/lib/active_record/tasks with the one in gist

and place the file ibm_db_database_tasks.rb on gist in $GEM_HOME/gems/activerecord-4.1.x/lib/active_record/tasks directory

and I have the next error:


[root@ITSTSMR01 alex]# rake db:migrate
rake aborted!
NameError: uninitialized constant ActiveRecord::Base::CollectionCacheKey
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/base.rb:289:in `<class:Base>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/base.rb:275:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/base.rb:25:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/mysql_database_tasks.rb:6:in `<class:MySQLDatabaseTasks>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/mysql_database_tasks.rb:3:in `<module:Tasks>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/mysql_database_tasks.rb:2:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/mysql_database_tasks.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:49:in `<module:DatabaseTasks>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:36:in `<module:Tasks>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:2:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-5.1.4/lib/active_record/railtie.rb:34:in `block (3 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => db:load_config
(See full trace by running task with --trace)

I don't know  what I have to do

thanks for all

**Comment by akhilravuri1** [comment]
Please feel to reopen this issue if you are facing this with the latest driver.
